spring:
  application:
    name: store
payment:
  default: paypal
  choice: stripe
stripe:
  currencies: USD, INR, GBP
  enabled: true
  apiUrl: https://api.stripe.com
  version: 1.2.3
  products: product1, product2, product3
